[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
ignore  = ['F401', 'W503']
per-file-ignores = [
    'bolt_app.py:E402',
]

[tool.isort]
profile = "black"
skip_gitignore = true