shared_memory:
  _target_: sherpa_ai.memory.shared_memory.SharedMemory
  objective: Generate a domain model from the user's description

user_id: none
team_id: none

llm:
  _target_: sherpa_ai.models.sherpa_base_chat_model.SherpaChatOpenAI
  model_name: gpt-3.5-turbo
  temperature: 0.7
  user_id: ${user_id}
  team_id: ${team_id}


agent_config:
  _target_: sherpa_ai.config.task_config.AgentConfig

deliberation:
  _target_: sherpa_ai.actions.deliberation.Deliberation
  role_description: You are a software modeler capable of creating a domain model from the user's description. Output the result in Umple code.
  llm: ${llm}

# The following customized actions are defined in verifiers.py
output_file:  
  _target_: verifiers.OutputModel
  filename: model.ump

generation:
  _target_: verifiers.UmpleGeneration


qa_agent:  # QA Agent customized to perform softwaare modeling with custom prompts
  _target_: sherpa_ai.agents.qa_agent.QAAgent
  llm: ${llm}
  shared_memory: ${shared_memory}
  name: QA Sherpa
  description: "You are a software modeler capable of creating a domain model from the user's description. 
Output the result in Umple code. Use -- for association and <@>- for aggregation. 
Include both classes and relationships.

In Umple, when generating relations, you only need to specify the relation in one of the classes. DO NOT specify the relation in both classes.

Here is an example of Umple code:

``` umple

namespace airline;

class Airline{
  1 <@>- * RegularFlight;
  1 <@>- * Person;
}

class RegularFlight{
  Time time;
  unique Integer flightNumber;
  1 -- * SpecificFlight;
}

class SpecificFlight{
  unique Date date;
}

class PassengerRole
{
  isA PersonRole;
  immutable String name ;
  1 -- * Booking;
}
  

class EmployeeRole
{
  String jobFunction ;
  isA PersonRole;
  * -- 0..1 EmployeeRole supervisor;
  * -- * SpecificFlight;
}

class Person
{
  settable String name;
  Integer idNumber;
  1 -- 0..2 PersonRole;
}

class PersonRole{}

class Booking{
  String seatNumber;
  * -- 1 SpecificFlight;
}

```

Do not include anything else
"
  agent_config: ${agent_config}
  num_runs: 1
  validation_steps: 10
  actions:
    - ${deliberation}
  validations:
    - ${output_file}
    - ${generation}
