name: Run offline tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "poetry"

      - name: Install dependencies
        working-directory: ./src
        run: |
          poetry install --with test,optional,lint

      - name: Run tests
        working-directory: ./src
        run:
          poetry run pytest --cov=sherpa_ai tests
